image: freebsd/14.x
packages:
  - gmake
  - llvm
  - binutils
  - valgrind
  - coreutils
  - wget
  - python3
  - py311-sqlite3
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      gmake test USE_VALGRIND=yes PROFILE=reldebug USE_SANITIZER=yes USE_EXTENSION_SUPPORT=yes KEFIR_END2END_SELECTIVE_VALGRIND=yes CC=clang
  - build: |
      cd kefir
      gmake clean
      gmake all PROFILE=reldebug CC=clang
  - gcc_torture: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/gcc-torture.test.done KEFIR_EXTERNAL_TEST_GCC_TORTURE_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
  - lua_tests: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/lua.test.done KEFIR_EXTERNAL_TEST_LUA_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
  - c_testsuite: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/c-testsuite.test.done KEFIR_EXTERNAL_TEST_C_TESTSUITE_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
  - bootstrap: |
      cd kefir
      gmake clean
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/kefir/bin/libs"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export REALPATH=grealpath
      LC_ALL=C.UTF-8 gmake bootstrap_test BOOTSTRAP_EXTRA_CFLAGS="-O1 -g" CC=clang
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
