image: netbsd/9.x
packages:
  - gmake
  - binutils
  - coreutils
  - bash
secrets:
  -  13fca65b-ffbd-4542-b2fe-6a2813e53256
sources:
  - https://git.sr.ht/~jprotopopov/kefir-private
tasks:
  - test: |
      cd kefir-private
      export LC_ALL=C.UTF-8
      gmake test all CC=gcc AS=gas PLATFORM=netbsd PROFILE=reldebug
  - bootstrap: |
      cd kefir-private
      gmake clean clean_bootstrap
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/kefir-private/bin/libs"
      export KEFIR_RTLIB="$HOME/kefir-private/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir-private/headers/kefir/runtime"
      export REALPATH=grealpath
      LC_ALL=C.UTF-8 gmake bootstrap BOOTSTRAP_EXTRA_CFLAGS="-O1" PLATFORM=netbsd
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
