image: netbsd/9.x
packages:
  - gmake
  - binutils
  - coreutils
  - bash
  - wget
  - python311
  - libatomic
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      export LC_ALL=C.UTF-8
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/pkg/lib
      export LIBRARY_PATH=$LIBRARY_PATH:/usr/pkg/lib
      gmake test all CC=gcc AS=gas PROFILE=reldebug
  - lua_tests: |
      cd kefir
      export LIBRARY_PATH=$LIBRARY_PATH:/usr/pkg/lib
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/lua.test.done REALPATH=grealpath KEFIR_EXTERNAL_TEST_LUA_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1 -D__ELF__=1 -include $HOME/kefir/headers/bootstrap_include/netbsd.h"
  - c_testsuite: |
      cd kefir
      mkdir -p "$HOME/bin"
      ln -s "$(which python3.11)" "$HOME/bin/python5"
      export PATH="$HOME/bin:$PATH"
      export LC_ALL=C.UTF-8 
      gmake bin/tests/external/c-testsuite.test.done KEFIR_EXTERNAL_TEST_C_TESTSUITE_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
  - gcc_torture: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/gcc-torture.test.done KEFIR_EXTERNAL_TEST_GCC_TORTURE_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1 -D__ELF__=1 -include $HOME/kefir/headers/bootstrap_include/netbsd.h" KEFIR_EXTERNAL_TEST_GCC_TORTURE_MAX_FAILED=537
  - bootstrap: |
      cd kefir
      gmake clean clean_bootstrap
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/pkg/lib:$HOME/kefir/bin/libs"
      export LIBRARY_PATH=$LIBRARY_PATH:/usr/pkg/lib
      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export REALPATH=grealpath
      LC_ALL=C.UTF-8 gmake bootstrap BOOTSTRAP_EXTRA_CFLAGS="-O1"
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
