image: openbsd/7.5
packages:
  - gmake
  - llvm
  - binutils
  - coreutils
  - bash
  - wget
  - python-3.11.8
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake test all CC=clang CCLD=clang AS=gas PROFILE=reldebug
  - lua_tests: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/lua.test.done KEFIR_EXTERNAL_TEST_LUA_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1 -include $HOME/kefir/headers/bootstrap_include/openbsd.h"
  - c_testsuite: |
      cd kefir
      mkdir -p "$HOME/bin"
      ln -s "$(which python3.11)" "$HOME/bin/python3"
      export PATH="$HOME/bin:$PATH"
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/c-testsuite.test.done KEFIR_EXTERNAL_TEST_C_TESTSUITE_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
  - gcc_torture: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake bin/tests/external/gcc-torture.test.done KEFIR_EXTERNAL_TEST_GCC_TORTURE_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1 -include $HOME/kefir/headers/bootstrap_include/openbsd.h" KEFIR_EXTERNAL_TEST_GCC_TORTURE_MAX_FAILED=545
  - bootstrap: |
      cd kefir
      gmake clean clean_bootstrap
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/kefir/bin/libs"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export REALPATH=grealpath
      LC_ALL=C.UTF-8 gmake bootstrap BOOTSTRAP_EXTRA_CFLAGS="-O1" CC=clang CCLD=clang AS=gas
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
