image: openbsd/7.2
packages:
  - gmake
  - llvm
  - binutils
  - gas
  - bash
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      export LC_ALL=C.UTF-8
      gmake test all CC=clang AS=gas PLATFORM=openbsd OPT=-O3
  - bootstrap: |
      cd kefir
      gmake clean clean_bootstrap
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/kefir/bin/libs"
      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export KEFIR_OPENBSD_INCLUDE="/usr/include;/usr/local/include"
      export KEFIR_OPENBSD_LIB="/usr/lib;/usr/local/lib"
      export KEFIR_OPENBSD_DYNAMIC_LINKER="/usr/lib/ld.so"
      export REALPATH=grealpath
      LC_ALL=C.UTF-8 gmake bootstrap KEFIR_EXTRAFLAGS="-O1" CC=clang AS=gas PLATFORM=openbsd
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
