image: ubuntu/noble
packages:
  - build-essential
  - gcc-12
  - clang-15
  - valgrind
  - wget
  - yasm
  - cmake
  - m4
sources:
  - https://git.sr.ht/~jprotopopov/kefir
  - https://github.com/csmith-project/csmith
tasks:
  - build_csmith: |
      mkdir csmith/build
      cd csmith/build
      cmake -DCMAKE_INSTALL_PREFIX=$HOME/csmith-install ..
      make -j$(nproc)
      make install
  - test_gcc: |
      cd kefir
      make clean
      export CSMITH=$HOME/csmith-install/bin/csmith
      LC_ALL=C.UTF-8 make test USE_EXTENSION_SUPPORT=yes USE_VALGRIND=yes PROFILE=reldebug USE_SANITIZER=yes KEFIR_END2END_SELECTIVE_VALGRIND=yes CC=gcc-12 -j$(nproc)
  - test_clang: |
      cd kefir
      make clean
      export CSMITH=$HOME/csmith-install/bin/csmith
      LC_ALL=C.UTF-8 make test USE_EXTENSION_SUPPORT=yes USE_VALGRIND=yes PROFILE=reldebug EXTRA_CFLAGS=-gdwarf-4 USE_SANITIZER=yes KEFIR_END2END_SELECTIVE_VALGRIND=yes CC=clang-15 -j$(nproc)
  - test_self: |
      cd kefir
      make clean
      make all CC=gcc-12 -j$(nproc)
      make install prefix=$HOME/kefir-install
      make clean
      make all PROFILE=reldebug USE_EXTENSION_SUPPORT=yes CC=$HOME/kefir-install/bin/kefir -j$(nproc)
      export CSMITH=$HOME/csmith-install/bin/csmith
      LC_ALL=C.UTF-8 make test USE_EXTENSION_SUPPORT=yes USE_VALGRIND=yes PROFILE=reldebug KEFIR_END2END_SELECTIVE_VALGRIND=yes CC=$HOME/kefir-install/bin/kefir -j$(nproc)
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
