image: ubuntu/focal
packages:
  - build-essential
  - gcc-10
  - clang-format
  - valgrind
  - xsltproc
  - wget
sources:
  - https://git.sr.ht/~jprotopopov/kefir
  - https://github.com/protopopov1122/c-testsuite.git
tasks:
  - kefircc: |
      cd kefir
      make all OPT=-O2 -j$(nproc)
  - lua_tests: |
      cd kefir
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/bin/libs
      export LC_ALL=C.UTF-8
      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export KEFIR_GNU_INCLUDE="/usr/lib/gcc/x86_64-linux-gnu/10/include;/usr/include/x86_64-linux-gnu;/usr/include;/usr/local/include"
      export KEFIR_GNU_LIB="/usr/lib/x86_64-linux-gnu;/usr/lib/gcc/x86_64-linux-gnu/10/;/usr/lib;/usr/local/lib"
      export KEFIR_GNU_DYNAMIC_LINKER="/lib64/ld-linux-x86-64.so.2"
      ./source/tests/misc/run-lua-tests.sh "$(pwd)/bin/kefir" "$(pwd)/bin/lua-test"
  - c_testsuite: |
      cd c-testsuite
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/kefir/bin/libs
      export KEFIRCC="$HOME/kefir/bin/kefir"
      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export KEFIR_GNU_INCLUDE="/usr/lib/gcc/x86_64-linux-gnu/10/include;/usr/include/x86_64-linux-gnu;/usr/include;/usr/local/include"
      export KEFIR_GNU_LIB="/usr/lib/x86_64-linux-gnu;/usr/lib/gcc/x86_64-linux-gnu/10/;/usr/lib;/usr/local/lib"
      export KEFIR_GNU_DYNAMIC_LINKER="/lib64/ld-linux-x86-64.so.2"
      export CFLAGS=""
      export LC_ALL=C.UTF-8 
      ./single-exec kefir | tee ~/c-tests.log
      [[ "x$(cat ~/c-tests.log | scripts/tapsummary | grep 'fail 0' | wc -l)" == "x1" ]] || exit 1
  - gcc_torture: |
      wget ftp://ftp.gnu.org/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.xz
      tar xvf gcc-11.2.0.tar.xz
      export TORTURE=$PWD/gcc-11.2.0/gcc/testsuite/gcc.c-torture
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/kefir/bin/libs
      export KEFIRCC="$HOME/kefir/bin/kefir"
      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      export KEFIR_GNU_INCLUDE="/usr/lib/gcc/x86_64-linux-gnu/10/include;/usr/include/x86_64-linux-gnu;/usr/include;/usr/local/include"
      export KEFIR_GNU_LIB="/usr/lib/x86_64-linux-gnu;/usr/lib/gcc/x86_64-linux-gnu/10/;/usr/lib;/usr/local/lib"
      export KEFIR_GNU_DYNAMIC_LINKER="/lib64/ld-linux-x86-64.so.2"
      ./kefir/source/tests/misc/run_gcc_torture_suite.sh 2>&1 | tee torture.log
      grep -v "Interrupted system call" torture.log | grep -i "fatal\|abort\|timeout\|segm" && exit 1 || true
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
