image: ubuntu/focal
packages:
  - build-essential
  - clang-10
  - valgrind
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      LC_ALL=C.UTF-8 make test MEMCHECK=yes OPT=-O3 SANITIZE=undefined CC=clang-10 -j$(nproc)
  - build: |
      cd kefir
      make clean
      LC_ALL=C.UTF-8 make all OPT=-O3 CC=clang-10
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
