image: ubuntu/jammy
packages:
  - build-essential
  - gcc-12
  - clang-15
  - valgrind
  - wget
sources:
  - https://git.sr.ht/~jprotopopov/kefir
  - https://git.sr.ht/~jprotopopov/c-testsuite
tasks:
  - test_gcc: |
      cd kefir
      make clean
      LC_ALL=C.UTF-8 make test USE_VALGRIND=yes PROFILE=reldebug USE_SANITIZER=yes CC=gcc-12 -j$(nproc)
  - test_clang: |
      cd kefir
      make clean
      LC_ALL=C.UTF-8 make test USE_VALGRIND=yes PROFILE=reldebug EXTRA_CFLAGS=-gdwarf-4 USE_SANITIZER=yes CC=clang-15 -j$(nproc)
  - build: |
      cd kefir
      make clean
      LC_ALL=C.UTF-8 make all PROFILE=reldebug CC=gcc-12
  - lua_tests: |
      cd kefir
      export LC_ALL=C.UTF-8
      make bin/tests/external/lua.test.done KEFIR_EXTERNAL_TEST_LUA_CFLAGS="-O1 -fPIC -pie"
  - c_testsuite: |
      cd kefir
      export LC_ALL=C.UTF-8
      make bin/tests/external/c-testsuite.test.done KEFIR_EXTERNAL_TEST_C_TESTSUITE_CFLAGS="-O1 -fPIC -pie"
  - gcc_torture: |
      cd kefir
      export LC_ALL=C.UTF-8
      make bin/tests/external/gcc-torture.test.done KEFIR_EXTERNAL_TEST_GCC_TORTURE_CFLAGS="-O1 -fPIC -pie" KEFIR_EXTERNAL_TEST_GCC_TORTURE_MAX_FAILED=544
  - bootstrap: |
      cd kefir
      make clean clean_bootstrap
      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
      LC_ALL=C.UTF-8 make bootstrap BOOTSTRAP_EXTRA_CFLAGS="-O1" -j$(nproc)
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
