KEFIR_DRIVER_SOURCE := $(wildcard $(SOURCE_DIR)/driver/*.c)

KEFIR_DRIVER_DEPENDENCIES := $(KEFIR_DRIVER_SOURCE:$(SOURCE_DIR)/%.c=$(BIN_DIR)/%.d)
KEFIR_DRIVER_OBJECT_FILES := $(KEFIR_DRIVER_SOURCE:$(SOURCE_DIR)/%.c=$(BIN_DIR)/%.o)
KEFIR_DRIVER_OBJECT_FILES += $(BIN_DIR)/driver/help.s.o

KEFIR_DRIVER_LIBS=
ifeq ($(SANITIZE),undefined)
KEFIR_DRIVER_LIBS=-fsanitize=undefined
endif

$(BIN_DIR)/driver/help.s.o: $(SOURCE_DIR)/driver/help.txt

$(KEFIR_EXE): $(KEFIR_DRIVER_OBJECT_FILES) $(LIBKEFIR_DEPENDENCY)
	@mkdir -p $(shell dirname "$@")
	@echo "Linking $@"
ifeq ($(USE_SHARED),yes)
	@$(LD) $(LDFLAGS) -o $@ $(KEFIR_DRIVER_OBJECT_FILES) $(KEFIR_DRIVER_LIBS) -L $(LIB_DIR) -lkefir
else
	@$(LD) $(LDFLAGS) -static -o $@ $(KEFIR_DRIVER_OBJECT_FILES) $(LIBKEFIR_A) $(KEFIR_DRIVER_LIBS)
endif

DEPENDENCIES += $(KEFIR_DRIVER_DEPENDENCIES)
OBJECT_FILES += $(KEFIR_DRIVER_OBJECT_FILES)
BINARIES += $(BIN_DIR)/kefir
