/*
    SPDX-License-Identifier: GPL-3.0

    Copyright (C) 2020-2026  Jevgenijs Protopopovs

    This file is part of Kefir project.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef KEFIR_CODEGEN_AMD64_INSTRUCTIONS_H_
#define KEFIR_CODEGEN_AMD64_INSTRUCTIONS_H_

#include "kefir/optimizer/code.h"

typedef struct kefir_codegen_amd64_function kefir_codegen_amd64_function_t;

// clang-format off
#define KEFIR_CODEGEN_AMD64_INSTRUCTIONS(_def, _separator)                                               \
    _def(get_argument, KEFIR_OPT_OPCODE_GET_ARGUMENT) _separator \
    _def(return, KEFIR_OPT_OPCODE_RETURN) _separator \
    _def(unreachable, KEFIR_OPT_OPCODE_UNREACHABLE) _separator \
    _def(get_part, KEFIR_OPT_OPCODE_GET_PART) _separator \
    _def(select, KEFIR_OPT_OPCODE_SELECT) _separator \
    _def(select_compare, KEFIR_OPT_OPCODE_SELECT_COMPARE) _separator \
    _def(int_const, KEFIR_OPT_OPCODE_INT_CONST) _separator \
    _def(uint_const, KEFIR_OPT_OPCODE_UINT_CONST) _separator \
    _def(float32_const, KEFIR_OPT_OPCODE_FLOAT32_CONST) _separator \
    _def(float64_const, KEFIR_OPT_OPCODE_FLOAT64_CONST) _separator \
    _def(long_double_const, KEFIR_OPT_OPCODE_LONG_DOUBLE_CONST) _separator \
    _def(string_ref, KEFIR_OPT_OPCODE_STRING_REF) _separator \
    _def(block_label, KEFIR_OPT_OPCODE_BLOCK_LABEL) _separator \
    _def(int_placeholder, KEFIR_OPT_OPCODE_INT_PLACEHOLDER) _separator \
    _def(float_placeholder, KEFIR_OPT_OPCODE_FLOAT32_PLACEHOLDER) _separator \
    _def(float_placeholder, KEFIR_OPT_OPCODE_FLOAT64_PLACEHOLDER) _separator \
    _def(temporary_object, KEFIR_OPT_OPCODE_TEMPORARY_OBJECT) _separator \
    _def(pair, KEFIR_OPT_OPCODE_PAIR) _separator \
    _def(local_lifetime_mark, KEFIR_OPT_OPCODE_LOCAL_LIFETIME_MARK) _separator \
    _def(local_scope, KEFIR_OPT_OPCODE_LOCAL_SCOPE) _separator \
    _def(alloc_local, KEFIR_OPT_OPCODE_ALLOC_LOCAL) _separator \
    _def(ref_local, KEFIR_OPT_OPCODE_REF_LOCAL) _separator \
    _def(get_global, KEFIR_OPT_OPCODE_GET_GLOBAL) _separator \
    _def(thread_local, KEFIR_OPT_OPCODE_GET_THREAD_LOCAL) _separator \
    _def(phi, KEFIR_OPT_OPCODE_PHI) _separator \
    _def(jump, KEFIR_OPT_OPCODE_JUMP) _separator \
    _def(branch, KEFIR_OPT_OPCODE_BRANCH) _separator \
    _def(branch_compare, KEFIR_OPT_OPCODE_BRANCH_COMPARE) _separator \
    _def(ijump, KEFIR_OPT_OPCODE_IJUMP) _separator \
    _def(int8_store, KEFIR_OPT_OPCODE_INT8_STORE) _separator \
    _def(int16_store, KEFIR_OPT_OPCODE_INT16_STORE) _separator \
    _def(int32_store, KEFIR_OPT_OPCODE_INT32_STORE) _separator \
    _def(int64_store, KEFIR_OPT_OPCODE_INT64_STORE) _separator \
    _def(int32_store, KEFIR_OPT_OPCODE_FLOAT32_STORE) _separator \
    _def(int64_store, KEFIR_OPT_OPCODE_FLOAT64_STORE) _separator \
    _def(long_double_store, KEFIR_OPT_OPCODE_LONG_DOUBLE_STORE) _separator \
    _def(int8_load, KEFIR_OPT_OPCODE_INT8_LOAD) _separator \
    _def(int16_load, KEFIR_OPT_OPCODE_INT16_LOAD) _separator \
    _def(int32_load, KEFIR_OPT_OPCODE_INT32_LOAD) _separator \
    _def(int64_load, KEFIR_OPT_OPCODE_INT64_LOAD) _separator \
    _def(float32_load, KEFIR_OPT_OPCODE_FLOAT32_LOAD) _separator \
    _def(float64_load, KEFIR_OPT_OPCODE_FLOAT64_LOAD) _separator \
    _def(long_double_load, KEFIR_OPT_OPCODE_LONG_DOUBLE_LOAD) _separator \
    _def(int_slot, KEFIR_OPT_OPCODE_INT_SLOT) _separator \
    _def(float_slot, KEFIR_OPT_OPCODE_FLOAT_SLOT) _separator \
    _def(slot_read, KEFIR_OPT_OPCODE_SLOT_READ) _separator \
    _def(slot_write, KEFIR_OPT_OPCODE_SLOT_WRITE) _separator \
    _def(int_to_float32, KEFIR_OPT_OPCODE_INT_TO_FLOAT32) _separator \
    _def(int_to_float64, KEFIR_OPT_OPCODE_INT_TO_FLOAT64) _separator \
    _def(uint_to_float, KEFIR_OPT_OPCODE_UINT_TO_FLOAT32) _separator \
    _def(uint_to_float, KEFIR_OPT_OPCODE_UINT_TO_FLOAT64) _separator \
    _def(float32_to_int, KEFIR_OPT_OPCODE_FLOAT32_TO_INT) _separator \
    _def(float64_to_int, KEFIR_OPT_OPCODE_FLOAT64_TO_INT) _separator \
    _def(float_to_uint, KEFIR_OPT_OPCODE_FLOAT32_TO_UINT) _separator \
    _def(float_to_uint, KEFIR_OPT_OPCODE_FLOAT64_TO_UINT) _separator \
    _def(float_to_float, KEFIR_OPT_OPCODE_FLOAT32_TO_FLOAT64) _separator \
    _def(float_to_float, KEFIR_OPT_OPCODE_FLOAT64_TO_FLOAT32) _separator \
    _def(float32_arith_op, KEFIR_OPT_OPCODE_FLOAT32_ADD) _separator \
    _def(float32_arith_op, KEFIR_OPT_OPCODE_FLOAT32_SUB) _separator \
    _def(float32_arith_op, KEFIR_OPT_OPCODE_FLOAT32_MUL) _separator \
    _def(float32_arith_op, KEFIR_OPT_OPCODE_FLOAT32_DIV) _separator \
    _def(float64_arith_op, KEFIR_OPT_OPCODE_FLOAT64_ADD) _separator \
    _def(float64_arith_op, KEFIR_OPT_OPCODE_FLOAT64_SUB) _separator \
    _def(float64_arith_op, KEFIR_OPT_OPCODE_FLOAT64_MUL) _separator \
    _def(float64_arith_op, KEFIR_OPT_OPCODE_FLOAT64_DIV) _separator \
    _def(float_unary_op, KEFIR_OPT_OPCODE_FLOAT32_NEG) _separator \
    _def(float_unary_op, KEFIR_OPT_OPCODE_FLOAT64_NEG) _separator \
    _def(long_double_binary_op, KEFIR_OPT_OPCODE_LONG_DOUBLE_ADD) _separator \
    _def(long_double_binary_op, KEFIR_OPT_OPCODE_LONG_DOUBLE_SUB) _separator \
    _def(long_double_binary_op, KEFIR_OPT_OPCODE_LONG_DOUBLE_MUL) _separator \
    _def(long_double_binary_op, KEFIR_OPT_OPCODE_LONG_DOUBLE_DIV) _separator \
    _def(long_double_neg, KEFIR_OPT_OPCODE_LONG_DOUBLE_NEG) _separator \
    _def(long_double_equals, KEFIR_OPT_OPCODE_LONG_DOUBLE_EQUALS) _separator \
    _def(long_double_greater, KEFIR_OPT_OPCODE_LONG_DOUBLE_GREATER) _separator \
    _def(long_double_less, KEFIR_OPT_OPCODE_LONG_DOUBLE_LESSER) _separator \
    _def(int_to_long_double, KEFIR_OPT_OPCODE_INT_TO_LONG_DOUBLE) _separator \
    _def(uint_to_long_double, KEFIR_OPT_OPCODE_UINT_TO_LONG_DOUBLE) _separator \
    _def(float32_to_long_double, KEFIR_OPT_OPCODE_FLOAT32_TO_LONG_DOUBLE) _separator \
    _def(float64_to_long_double, KEFIR_OPT_OPCODE_FLOAT64_TO_LONG_DOUBLE) _separator \
    _def(long_double_to_int, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_INT) _separator \
    _def(long_double_to_uint, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_UINT) _separator \
    _def(long_double_to_float32, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_FLOAT32) _separator \
    _def(long_double_to_float64, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_FLOAT64) _separator \
    _def(bits_extract_signed, KEFIR_OPT_OPCODE_BITS_EXTRACT_SIGNED) _separator \
    _def(bits_extract_unsigned, KEFIR_OPT_OPCODE_BITS_EXTRACT_UNSIGNED) _separator \
    _def(bits_insert, KEFIR_OPT_OPCODE_BITS_INSERT) _separator \
    _def(copy_memory, KEFIR_OPT_OPCODE_COPY_MEMORY) _separator \
    _def(zero_memory, KEFIR_OPT_OPCODE_ZERO_MEMORY) _separator \
    _def(stack_alloc, KEFIR_OPT_OPCODE_STACK_ALLOC) _separator \
    _def(push_scope, KEFIR_OPT_OPCODE_SCOPE_PUSH) _separator \
    _def(pop_scope, KEFIR_OPT_OPCODE_SCOPE_POP) _separator \
    _def(invoke, KEFIR_OPT_OPCODE_INVOKE) _separator \
    _def(invoke, KEFIR_OPT_OPCODE_INVOKE_VIRTUAL) _separator \
    _def(tail_invoke, KEFIR_OPT_OPCODE_TAIL_INVOKE) _separator \
    _def(tail_invoke, KEFIR_OPT_OPCODE_TAIL_INVOKE_VIRTUAL) _separator \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_ADD) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_ADD) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_ADD) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_ADD) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_SUB) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_SUB) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_SUB) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_SUB) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_UINT8_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_UINT16_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_UINT32_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_UINT64_MUL) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_AND) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_AND) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_AND) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_AND) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_OR) _separator                                                     \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_OR) _separator                                                     \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_OR) _separator                                                     \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_OR) _separator                                                     \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_XOR) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_XOR) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_XOR) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_XOR) _separator                                                   \
    _def(int_div, KEFIR_OPT_OPCODE_INT8_DIV) _separator                                                   \
    _def(int_div, KEFIR_OPT_OPCODE_INT16_DIV) _separator                                                   \
    _def(int_div, KEFIR_OPT_OPCODE_INT32_DIV) _separator                                                   \
    _def(int_div, KEFIR_OPT_OPCODE_INT64_DIV) _separator                                                   \
    _def(int_mod, KEFIR_OPT_OPCODE_INT8_MOD) _separator                                                   \
    _def(int_mod, KEFIR_OPT_OPCODE_INT16_MOD) _separator                                                   \
    _def(int_mod, KEFIR_OPT_OPCODE_INT32_MOD) _separator                                                   \
    _def(int_mod, KEFIR_OPT_OPCODE_INT64_MOD) _separator                                                   \
    _def(uint_div, KEFIR_OPT_OPCODE_UINT8_DIV) _separator                                                   \
    _def(uint_div, KEFIR_OPT_OPCODE_UINT16_DIV) _separator                                                   \
    _def(uint_div, KEFIR_OPT_OPCODE_UINT32_DIV) _separator                                                   \
    _def(uint_div, KEFIR_OPT_OPCODE_UINT64_DIV) _separator                                                   \
    _def(uint_mod, KEFIR_OPT_OPCODE_UINT8_MOD) _separator                                                   \
    _def(uint_mod, KEFIR_OPT_OPCODE_UINT16_MOD) _separator                                                   \
    _def(uint_mod, KEFIR_OPT_OPCODE_UINT32_MOD) _separator                                                   \
    _def(uint_mod, KEFIR_OPT_OPCODE_UINT64_MOD) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_LSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_LSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_LSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_LSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_RSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_RSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_RSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_RSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_ARSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_ARSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_ARSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_ARSHIFT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_NOT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_NOT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_NOT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_NOT) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT8_NEG) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT16_NEG) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT32_NEG) _separator                                                   \
    _def(int_arithmetics, KEFIR_OPT_OPCODE_INT64_NEG) _separator                                                   \
    _def(int_comparison, KEFIR_OPT_OPCODE_SCALAR_COMPARE) _separator                                                   \
    _def(int_bool_not, KEFIR_OPT_OPCODE_INT8_BOOL_NOT) _separator                                                   \
    _def(int_bool_not, KEFIR_OPT_OPCODE_INT16_BOOL_NOT) _separator                                                   \
    _def(int_bool_not, KEFIR_OPT_OPCODE_INT32_BOOL_NOT) _separator                                                   \
    _def(int_bool_not, KEFIR_OPT_OPCODE_INT64_BOOL_NOT) _separator                                                   \
    _def(int_bool_or, KEFIR_OPT_OPCODE_INT8_BOOL_OR) _separator                                                   \
    _def(int_bool_or, KEFIR_OPT_OPCODE_INT16_BOOL_OR) _separator                                                   \
    _def(int_bool_or, KEFIR_OPT_OPCODE_INT32_BOOL_OR) _separator                                                   \
    _def(int_bool_or, KEFIR_OPT_OPCODE_INT64_BOOL_OR) _separator                                                   \
    _def(int_bool_and, KEFIR_OPT_OPCODE_INT8_BOOL_AND) _separator                                                   \
    _def(int_bool_and, KEFIR_OPT_OPCODE_INT16_BOOL_AND) _separator                                                   \
    _def(int_bool_and, KEFIR_OPT_OPCODE_INT32_BOOL_AND) _separator                                                   \
    _def(int_bool_and, KEFIR_OPT_OPCODE_INT64_BOOL_AND) _separator                                                   \
    _def(int_to_bool, KEFIR_OPT_OPCODE_INT8_TO_BOOL) _separator                          \
    _def(int_to_bool, KEFIR_OPT_OPCODE_INT16_TO_BOOL) _separator                          \
    _def(int_to_bool, KEFIR_OPT_OPCODE_INT32_TO_BOOL) _separator                          \
    _def(int_to_bool, KEFIR_OPT_OPCODE_INT64_TO_BOOL) _separator                          \
    _def(int_zero_extend8, KEFIR_OPT_OPCODE_INT64_ZERO_EXTEND_8BITS) _separator                          \
    _def(int_zero_extend16, KEFIR_OPT_OPCODE_INT64_ZERO_EXTEND_16BITS) _separator                        \
    _def(int_zero_extend32, KEFIR_OPT_OPCODE_INT64_ZERO_EXTEND_32BITS) _separator                        \
    _def(int_sign_extend8, KEFIR_OPT_OPCODE_INT64_SIGN_EXTEND_8BITS) _separator                          \
    _def(int_sign_extend16, KEFIR_OPT_OPCODE_INT64_SIGN_EXTEND_16BITS) _separator                        \
    _def(int_sign_extend32, KEFIR_OPT_OPCODE_INT64_SIGN_EXTEND_32BITS) _separator \
    _def(vararg_start, KEFIR_OPT_OPCODE_VARARG_START) _separator \
    _def(vararg_end, KEFIR_OPT_OPCODE_VARARG_END) _separator \
    _def(vararg_copy, KEFIR_OPT_OPCODE_VARARG_COPY) _separator \
    _def(vararg_get, KEFIR_OPT_OPCODE_VARARG_GET) _separator \
    _def(fenv_save, KEFIR_OPT_OPCODE_FENV_SAVE) _separator \
    _def(fenv_clear, KEFIR_OPT_OPCODE_FENV_CLEAR) _separator \
    _def(fenv_update, KEFIR_OPT_OPCODE_FENV_UPDATE) _separator \
    _def(complex_float32_from, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_FROM) _separator \
    _def(complex_float32_real, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_REAL) _separator \
    _def(complex_float32_imaginary, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_IMAGINARY) _separator \
    _def(complex_float64_from, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_FROM) _separator \
    _def(complex_float64_real, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_REAL) _separator \
    _def(complex_float64_imaginary, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_IMAGINARY) _separator \
    _def(complex_long_double_from, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_FROM) _separator \
    _def(complex_long_double_real, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_REAL) _separator \
    _def(complex_long_double_imaginary, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_IMAGINARY) _separator \
    _def(complex_float32_equals, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_EQUALS) _separator \
    _def(complex_float64_equals, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_EQUALS) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_EQUALS) _separator \
    _def(complex_float32_truncate_1bit, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_TRUNCATE_1BIT) _separator \
    _def(complex_float64_truncate_1bit, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_TRUNCATE_1BIT) _separator \
    _def(long_double_pair_truncate_1bit, KEFIR_OPT_OPCODE_LONG_DOUBLE_PAIR_TRUNCATE_1BIT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_TRUNCATE_1BIT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_SUB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_SUB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_SUB) _separator \
    _def(complex_float32_mul, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_MUL) _separator \
    _def(complex_float32_div, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_DIV) _separator \
    _def(complex_float64_mul, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_MUL) _separator \
    _def(complex_float64_div, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_DIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_MUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_DIV) _separator \
    _def(complex_float32_neg, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_NEG) _separator \
    _def(complex_float64_neg, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_NEG) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_NEG) _separator \
    _def(complex_float32_load, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_LOAD) _separator \
    _def(complex_float64_load, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_LOAD) _separator \
    _def(complex_float32_store, KEFIR_OPT_OPCODE_COMPLEX_FLOAT32_STORE) _separator \
    _def(complex_float64_store, KEFIR_OPT_OPCODE_COMPLEX_FLOAT64_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_COMPLEX_LONG_DOUBLE_STORE) _separator \
    _def(atomic_load, KEFIR_OPT_OPCODE_ATOMIC_LOAD8) _separator \
    _def(atomic_load, KEFIR_OPT_OPCODE_ATOMIC_LOAD16) _separator \
    _def(atomic_load, KEFIR_OPT_OPCODE_ATOMIC_LOAD32) _separator \
    _def(atomic_load, KEFIR_OPT_OPCODE_ATOMIC_LOAD64) _separator \
    _def(atomic_load_long_double, KEFIR_OPT_OPCODE_ATOMIC_LOAD_LONG_DOUBLE) _separator \
    _def(atomic_load_complex, KEFIR_OPT_OPCODE_ATOMIC_LOAD_COMPLEX_FLOAT32) _separator \
    _def(atomic_load_complex, KEFIR_OPT_OPCODE_ATOMIC_LOAD_COMPLEX_FLOAT64) _separator \
    _def(atomic_load_complex, KEFIR_OPT_OPCODE_ATOMIC_LOAD_COMPLEX_LONG_DOUBLE) _separator \
    _def(atomic_store, KEFIR_OPT_OPCODE_ATOMIC_STORE8) _separator \
    _def(atomic_store, KEFIR_OPT_OPCODE_ATOMIC_STORE16) _separator \
    _def(atomic_store, KEFIR_OPT_OPCODE_ATOMIC_STORE32) _separator \
    _def(atomic_store, KEFIR_OPT_OPCODE_ATOMIC_STORE64) _separator \
    _def(atomic_store_long_double, KEFIR_OPT_OPCODE_ATOMIC_STORE_LONG_DOUBLE) _separator \
    _def(atomic_store_complex_float, KEFIR_OPT_OPCODE_ATOMIC_STORE_COMPLEX_FLOAT32) _separator \
    _def(atomic_store_complex_float, KEFIR_OPT_OPCODE_ATOMIC_STORE_COMPLEX_FLOAT64) _separator \
    _def(atomic_store_complex_long_double, KEFIR_OPT_OPCODE_ATOMIC_STORE_COMPLEX_LONG_DOUBLE) _separator \
    _def(atomic_copy_memory, KEFIR_OPT_OPCODE_ATOMIC_COPY_MEMORY_FROM) _separator \
    _def(atomic_copy_memory, KEFIR_OPT_OPCODE_ATOMIC_COPY_MEMORY_TO) _separator \
    _def(atomic_compare_exchange, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG8) _separator \
    _def(atomic_compare_exchange, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG16) _separator \
    _def(atomic_compare_exchange, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG32) _separator \
    _def(atomic_compare_exchange, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG64) _separator \
    _def(atomic_compare_exchange_long_double, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG_LONG_DOUBLE) _separator \
    _def(atomic_compare_exchange_complex_float, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG_COMPLEX_FLOAT32) _separator \
    _def(atomic_compare_exchange_complex_float, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG_COMPLEX_FLOAT64) _separator \
    _def(atomic_compare_exchange_complex_long_double, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG_COMPLEX_LONG_DOUBLE) _separator \
    _def(atomic_compare_exchange_memory, KEFIR_OPT_OPCODE_ATOMIC_CMPXCHG_MEMORY) _separator \
    _def(add_overflow, KEFIR_OPT_OPCODE_ADD_OVERFLOW) _separator \
    _def(sub_overflow, KEFIR_OPT_OPCODE_SUB_OVERFLOW) _separator \
    _def(mul_overflow, KEFIR_OPT_OPCODE_MUL_OVERFLOW) _separator \
    _def(bitint_const, KEFIR_OPT_OPCODE_BITINT_SIGNED_CONST) _separator \
    _def(bitint_const, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_CONST) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_GET_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_GET_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_FROM_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_FROM_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_CAST_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_CAST_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SIGNED_TO_FLOAT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_TO_FLOAT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SIGNED_TO_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_TO_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SIGNED_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT_TO_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT_TO_BITINT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DOUBLE_TO_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DOUBLE_TO_BITINT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_BITINT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_TO_BOOL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_LOAD_PRECISE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_STORE_PRECISE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_ATOMIC_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_ATOMIC_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_ATOMIC_COMPARE_EXCHANGE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_NEGATE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_INVERT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BOOL_NOT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SUB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_IMUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UMUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_IDIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UDIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_IMOD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UMOD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_LSHIFT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_RSHIFT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_ARSHIFT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_AND) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_OR) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_XOR) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_EQUAL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_GREATER) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_ABOVE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_LESS) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BELOW) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_EXTRACT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_EXTRACT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_INSERT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BUILTIN_FFS) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BUILTIN_CLZ) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BUILTIN_CTZ) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BUILTIN_CLRSB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BUILTIN_POPCOUNT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_BUILTIN_PARITY) _separator \
    _def(decimal_const, KEFIR_OPT_OPCODE_DECIMAL32_CONST) _separator \
    _def(decimal_const, KEFIR_OPT_OPCODE_DECIMAL64_CONST) _separator \
    _def(decimal_const, KEFIR_OPT_OPCODE_DECIMAL128_CONST) _separator \
    _def(decimal_load, KEFIR_OPT_OPCODE_DECIMAL32_LOAD) _separator \
    _def(decimal_load, KEFIR_OPT_OPCODE_DECIMAL64_LOAD) _separator \
    _def(decimal_load, KEFIR_OPT_OPCODE_DECIMAL128_LOAD) _separator \
    _def(decimal_store, KEFIR_OPT_OPCODE_DECIMAL32_STORE) _separator \
    _def(decimal_store, KEFIR_OPT_OPCODE_DECIMAL64_STORE) _separator \
    _def(decimal_store, KEFIR_OPT_OPCODE_DECIMAL128_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_ADD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_SUB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_SUB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_SUB) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_MUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_MUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_MUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_DIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_DIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_DIV) _separator \
    _def(decimal_neg32, KEFIR_OPT_OPCODE_DECIMAL32_NEG) _separator \
    _def(decimal_neg64, KEFIR_OPT_OPCODE_DECIMAL64_NEG) _separator \
    _def(decimal_neg128, KEFIR_OPT_OPCODE_DECIMAL128_NEG) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_EQUAL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_EQUAL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_EQUAL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_GREATER) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_GREATER) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_GREATER) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_LESS) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_LESS) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_LESS) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT32_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT64_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT32_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT64_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT32_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_FLOAT64_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_LONG_DOUBLE_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_INT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_UINT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_INT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_UINT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_INT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_UINT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_UINT_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_UINT_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_UINT_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_TO_BITINT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_TO_BITINT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_TO_BITINT_UNSIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SIGNED_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SIGNED_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_SIGNED_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_BITINT_UNSIGNED_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_ATOMIC_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_ATOMIC_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_ATOMIC_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_ATOMIC_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_ATOMIC_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_ATOMIC_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_ATOMIC_CMPXCHG) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_ATOMIC_CMPXCHG) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_ATOMIC_CMPXCHG) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL32_ISNAN) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL64_ISNAN) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_DECIMAL128_ISNAN) _separator \
    _def(int128_to_bool, KEFIR_OPT_OPCODE_INT128_TO_BOOL) _separator \
    _def(int128_trunacate_int64, KEFIR_OPT_OPCODE_INT128_TRUNCATE_INT64) _separator \
    _def(int128_zero_extend_64bits, KEFIR_OPT_OPCODE_INT128_ZERO_EXTEND_64BITS) _separator \
    _def(int128_sign_extend_64bits, KEFIR_OPT_OPCODE_INT128_SIGN_EXTEND_64BITS) _separator \
    _def(int128_load, KEFIR_OPT_OPCODE_INT128_LOAD) _separator \
    _def(int128_store, KEFIR_OPT_OPCODE_INT128_STORE) _separator \
    _def(int128_add, KEFIR_OPT_OPCODE_INT128_ADD) _separator \
    _def(int128_sub, KEFIR_OPT_OPCODE_INT128_SUB) _separator \
    _def(int128_mul, KEFIR_OPT_OPCODE_INT128_IMUL) _separator \
    _def(int128_mul, KEFIR_OPT_OPCODE_INT128_UMUL) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_IDIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UDIV) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_IMOD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UMOD) _separator \
    _def(int128_lshift, KEFIR_OPT_OPCODE_INT128_LSHIFT) _separator \
    _def(int128_rshift, KEFIR_OPT_OPCODE_INT128_RSHIFT) _separator \
    _def(int128_arshift, KEFIR_OPT_OPCODE_INT128_ARSHIFT) _separator \
    _def(int128_and, KEFIR_OPT_OPCODE_INT128_AND) _separator \
    _def(int128_or, KEFIR_OPT_OPCODE_INT128_OR) _separator \
    _def(int128_xor, KEFIR_OPT_OPCODE_INT128_XOR) _separator \
    _def(int128_equal, KEFIR_OPT_OPCODE_INT128_EQUAL) _separator \
    _def(int128_greater, KEFIR_OPT_OPCODE_INT128_GREATER) _separator \
    _def(int128_less, KEFIR_OPT_OPCODE_INT128_LESS) _separator \
    _def(int128_above, KEFIR_OPT_OPCODE_INT128_ABOVE) _separator \
    _def(int128_below, KEFIR_OPT_OPCODE_INT128_BELOW) _separator \
    _def(int128_neg, KEFIR_OPT_OPCODE_INT128_NEG) _separator \
    _def(int128_not, KEFIR_OPT_OPCODE_INT128_NOT) _separator \
    _def(int128_bool_not, KEFIR_OPT_OPCODE_INT128_BOOL_NOT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_ATOMIC_LOAD) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_ATOMIC_STORE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_ATOMIC_CMPXCHG) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_TO_BITINT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_TO_BITINT) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_FROM_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_FROM_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_FROM_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_FROM_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_FROM_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_SIGNED_FROM_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_FROM_BITINT_SIGNED) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_FROM_FLOAT32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_FROM_FLOAT64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_FROM_LONG_DOUBLE) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_FROM_DECIMAL32) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_FROM_DECIMAL64) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_UNSIGNED_FROM_DECIMAL128) _separator \
    _def(error_lowered, KEFIR_OPT_OPCODE_INT128_FROM_BITINT_UNSIGNED) _separator \
    _def(int128_lower_half, KEFIR_OPT_OPCODE_INT128_LOWER_HALF) _separator \
    _def(int128_upper_half, KEFIR_OPT_OPCODE_INT128_UPPER_HALF) _separator \
    _def(int128_from, KEFIR_OPT_OPCODE_INT128_FROM) _separator \
    _def(inline_assembly, KEFIR_OPT_OPCODE_INLINE_ASSEMBLY)
// clang-format on

#define KEFIR_CODEGEN_AMD64_INSTRUCTION_IMPL(_id) kefir_codegen_amd64_translate_##_id

#define DECL_INSTR(_id, _opcode)                              \
    kefir_result_t KEFIR_CODEGEN_AMD64_INSTRUCTION_IMPL(_id)( \
        struct kefir_mem *, struct kefir_codegen_amd64_function *, const struct kefir_opt_instruction *)
KEFIR_CODEGEN_AMD64_INSTRUCTIONS(DECL_INSTR, ;);
#undef DECL_INSTR

kefir_result_t kefir_codegen_amd64_function_translate_instruction(struct kefir_mem *, struct kefir_codegen_amd64_function *,
                                            const struct kefir_opt_instruction *);

#endif
