/*
    SPDX-License-Identifier: GPL-3.0

    Copyright (C) 2020-2026  Jevgenijs Protopopovs

    This file is part of Kefir project.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#define PRINT_VAL(_x) #_x = _x

PRINT_VAL(__FLOAT_WORD_ORDER__)
PRINT_VAL(__FLT_RADIX__)
PRINT_VAL(__FLT_MANT_DIG__)
PRINT_VAL(__DBL_MANT_DIG__)
PRINT_VAL(__LDBL_MANT_DIG__)
PRINT_VAL(__FLT_DIG__)
PRINT_VAL(__DBL_DIG__)
PRINT_VAL(__LDBL_DIG__)
PRINT_VAL(__FLT_DECIMAL_DIG__)
PRINT_VAL(__DBL_DECIMAL_DIG__)
PRINT_VAL(__LDBL_DECIMAL_DIG__)
PRINT_VAL(__FLT_MIN_EXP__)
PRINT_VAL(__DBL_MIN_EXP__)
PRINT_VAL(__LDBL_MIN_EXP__)
PRINT_VAL(__FLT_MIN_10_EXP__)
PRINT_VAL(__DBL_MIN_10_EXP__)
PRINT_VAL(__LDBL_MIN_10_EXP__)
PRINT_VAL(__FLT_MAX_EXP__)
PRINT_VAL(__DBL_MAX_EXP__)
PRINT_VAL(__LDBL_MAX_EXP__)
PRINT_VAL(__FLT_MAX_10_EXP__)
PRINT_VAL(__DBL_MAX_10_EXP__)
PRINT_VAL(__LDBL_MAX_10_EXP__)
PRINT_VAL(__FLT_MIN__)
PRINT_VAL(__DBL_MIN__)
PRINT_VAL(__LDBL_MIN__)
PRINT_VAL(__FLT_EPSILON__)
PRINT_VAL(__DBL_EPSILON__)
PRINT_VAL(__LDBL_EPSILON__)
PRINT_VAL(__FLT_MAX__)
PRINT_VAL(__DBL_MAX__)
PRINT_VAL(__LDBL_MAX__)
PRINT_VAL(__FLT_EVAL_METHOD__)
PRINT_VAL(__FLT_EVAL_METHOD_TS_18661_3__)
PRINT_VAL(__DECIMAL_DIG__)
PRINT_VAL(__FLT_HAS_DENORM__)
PRINT_VAL(__DBL_HAS_DENORM__)
PRINT_VAL(__LDBL_HAS_DENORM__)
PRINT_VAL(__FLT_DENORM_MIN__)
PRINT_VAL(__DBL_DENORM_MIN__)
PRINT_VAL(__LDBL_DENORM_MIN__)
PRINT_VAL(__FLT_NORM_MAX__)
PRINT_VAL(__DBL_NORM_MAX__)
PRINT_VAL(__LDBL_NORM_MAX__)
PRINT_VAL(__FLT_IS_IEC_60559__)
PRINT_VAL(__DBL_IS_IEC_60559__)
PRINT_VAL(__LDBL_IS_IEC_60559__)

PRINT_VAL(__DEC32_EPSILON__)
PRINT_VAL(__DEC32_MAX__)
PRINT_VAL(__DEC32_MIN_EXP__)
PRINT_VAL(__DEC32_MIN__)
PRINT_VAL(__DEC32_SUBNORMAL_MIN__)
PRINT_VAL(__DEC32_MAX_EXP__)
PRINT_VAL(__DEC32_MANT_DIG__)
PRINT_VAL(__DEC64_MAX_EXP__)
PRINT_VAL(__DEC64_MIN_EXP__)
PRINT_VAL(__DEC64_EPSILON__)
PRINT_VAL(__DEC64_MAX__)
PRINT_VAL(__DEC64_MANT_DIG__)
PRINT_VAL(__DEC64_MIN__)
PRINT_VAL(__DEC64_SUBNORMAL_MIN__)
PRINT_VAL(__DEC128_EPSILON__)
PRINT_VAL(__DEC128_MIN__)
PRINT_VAL(__DEC128_MIN_EXP__)
PRINT_VAL(__DEC128_MAX__)
PRINT_VAL(__DEC128_MAX_EXP__)
PRINT_VAL(__DEC128_SUBNORMAL_MIN__)
PRINT_VAL(__DEC128_MANT_DIG__)
PRINT_VAL(__DEC64X_MAX_EXP__)
PRINT_VAL(__DEC64X_MAX__)
PRINT_VAL(__DEC64X_MIN__)
PRINT_VAL(__DEC64X_MANT_DIG__)
PRINT_VAL(__DEC64X_EPSILON__)
PRINT_VAL(__DEC64X_SUBNORMAL_MIN__)
PRINT_VAL(__DEC64X_MIN_EXP__)
PRINT_VAL(__DEC_EVAL_METHOD__)

PRINT_VAL(__KEFIRCC_DECIMAL_SUPPORT_BID__)
PRINT_VAL(__KEFIRCC_DECIMAL_SUPPORT_DPD__)
