KEFIR_STANDALONE_SOURCE := $(SOURCE_DIR)/main/standalone.c \
	                       $(SOURCE_DIR)/driver/runner.c

KEFIR_STANDALONE_DEPENDENCIES := $(KEFIR_STANDALONE_SOURCE:$(SOURCE_DIR)/%.c=$(BIN_DIR)/%.d)
KEFIR_STANDALONE_OBJECT_FILES := $(KEFIR_STANDALONE_SOURCE:$(SOURCE_DIR)/%.c=$(BIN_DIR)/%.o)
KEFIR_STANDALONE_OBJECT_FILES += $(BIN_DIR)/driver/help.s.o

KEFIR_STANDALONE_LINKED_LIBS=
ifeq ($(SANITIZE),undefined)
KEFIR_STANDALONE_LINKED_LIBS=-fsanitize=undefined
endif

$(BIN_DIR)/driver/help.s.o: $(SOURCE_DIR)/driver/help.txt

$(BIN_DIR)/kefir: $(KEFIR_STANDALONE_OBJECT_FILES) $(LIBKEFIR_SO)
	@mkdir -p $(shell dirname "$@")
	@echo "Linking $@"
	@$(CC) -o $@ $(KEFIR_STANDALONE_OBJECT_FILES) $(KEFIR_STANDALONE_LINKED_LIBS) -L $(LIB_DIR) -lkefir

DEPENDENCIES += $(KEFIR_STANDALONE_DEPENDENCIES)
OBJECT_FILES += $(KEFIR_STANDALONE_OBJECT_FILES)
BINARIES += $(BIN_DIR)/kefir
