#ifndef KEFIR_CODEGEN_OPT_SYSTEM_V_AMD64_RUNTIME_H_
#define KEFIR_CODEGEN_OPT_SYSTEM_V_AMD64_RUNTIME_H_

#include "kefir/core/basic-types.h"

#define KEFIR_AMD64_THREAD_LOCAL "%s@tpoff"
#define KEFIR_AMD64_THREAD_LOCAL_GOT "%s@gottpoff"
#define KEFIR_AMD64_EMUTLS_V "__emutls_v.%s"
#define KEFIR_AMD64_EMUTLS_T "__emutls_t.%s"
#define KEFIR_AMD64_EMUTLS_GOT "__emutls_v.%s@GOTPCREL"
#define KEFIR_AMD64_EMUTLS_GET_ADDR "__emutls_get_address@PLT"
#define KEFIR_AMD64_SYSTEM_V_STRING_LITERAL "__kefir_string_literal" KEFIR_ID_FMT
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_STRING_LITERAL "__kefirrt_string_literal" KEFIR_ID_FMT
#define KEFIR_OPT_AMD64_SYSTEM_V_FUNCTION_BLOCK "__kefir_func_%s_block" KEFIR_ID_FMT
#define KEFIR_OPT_AMD64_SYSTEM_V_FUNCTION_BLOCK_LABEL "__kefir_func_%s_block" KEFIR_ID_FMT "_label" KEFIR_ID_FMT
#define KEFIR_OPT_AMD64_SYSTEM_V_FUNCTION_CONSTANT_LABEL "__kefir_func_%s_const" KEFIR_ID_FMT
#define KEFIR_OPT_AMD64_SYSTEM_V_FUNCTION_CONSTANT_FLOAT32_NEG "__kefir_func_%s_f32neg"
#define KEFIR_OPT_AMD64_SYSTEM_V_FUNCTION_CONSTANT_FLOAT64_NEG "__kefir_func_%s_f64neg"
#define KEFIR_OPT_AMD64_SYSTEM_V_FUNCTION_CONSTANT_UINT_TO_LD "__kefir_func_%s_uint2ld"

#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_SAVE_REGISTERS "__kefirrt_opt_save_registers"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_LOAD_INT_VARARG "__kefirrt_opt_load_int_vararg"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_LOAD_SSE_VARARG "__kefirrt_opt_load_sse_vararg"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_FLOAT32_TO_UINT "__kefirrt_opt_float32_to_uint"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_FLOAT64_TO_UINT "__kefirrt_opt_float64_to_uint"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_LONG_DOUBLE_TO_INT "__kefirrt_opt_long_double_to_int"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_LONG_DOUBLE_TO_UINT "__kefirrt_opt_long_double_to_uint"
#define KEFIR_OPT_AMD64_SYSTEM_V_RUNTIME_LONG_DOUBLE_TRUNC_1BIT "__kefirrt_opt_long_double_trunc_1bit"

#endif
