image: ubuntu/jammy
packages:
  - build-essential
  - gcc-12
  - yacc
  - libncurses-dev
  - zlib1g-dev
  - gettext
  - file
  - wget
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - build: |
      cd kefir
      make clean
      LC_ALL=C.UTF-8 make all PROFILE=reldebug CC=gcc-12 -j$(nproc)
  - test_bash: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/bash.test.done -j$(nproc)
  - test_c_testsuite: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/c-testsuite.test.done -j$(nproc)
  - test_gcc_torture: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/gcc-torture.test.done -j$(nproc)
  - test_git: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/git.test.done -j$(nproc)
  - test_libsir: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/libsir.test.done -j$(nproc)
  - test_lua: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/lua.test.done -j$(nproc)
  - test_musl: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/musl.test.done -j$(nproc)
  - test_nano: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/nano.test.done -j$(nproc)
  - test_oksh: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/oksh.test.done -j$(nproc)
  - test_sqlite: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/sqlite.test.done -j$(nproc)
  - test_tcc: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/tcc.test.done -j$(nproc)
  # Disabled due to OOM
  # - test_tcl: |
  #     cd kefir
  #     LC_ALL=C.UTF-8 make bin/tests/external/tcl.test.done -j$(nproc)
  - test_tin: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/tin.test.done -j$(nproc)
  - test_yasm: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/yasm.test.done -j$(nproc)
  - test_zlib: |
      cd kefir
      LC_ALL=C.UTF-8 make bin/tests/external/zlib.test.done -j$(nproc)
triggers:
  - action: email
    condition: failure
    to: jevgenij@protopopov.lv
